<?php include 'header.php'; ?>
<?php include 'stickybar.php'; ?>
<?php include 'search-canvas.php'; ?>
<?php include 'happy-clients.php'; ?>
<?php include 'learning-paths.php'; ?>
<?php include 'affiliated-institute.php'; ?>
<?php include 'mentors.php'; ?>
<?php include 'why-choose-us.php'; ?>
<?php include 'featured.php'; ?>
<?php include 'appdownload.php'; ?>
<?php include 'footer.php'; ?>